//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compose
    {
        public int compose_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> set_id { get; set; }
        public Nullable<int> product_amount { get; set; }
    
        public virtual ProductNew ProductNew { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
