//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_addr { get; set; }
        public Nullable<double> employee_salary { get; set; }
        public Nullable<System.DateTime> employee_date { get; set; }
        public string employee_tel { get; set; }
        public byte[] employee_picture { get; set; }
        public string employee_position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
