//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int rec_id { get; set; }
        public double rec_sum { get; set; }
        public string rec_number { get; set; }
        public System.DateTime rec_date { get; set; }
        public int rec_amount { get; set; }
        public string employee_ID { get; set; }
        public string member_ID { get; set; }
        public string product_ID { get; set; }
        public string set_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual ProductNew ProductNew { get; set; }
        public virtual ProductNew ProductNew1 { get; set; }
        public virtual ProductSet ProductSet { get; set; }
        public virtual ProductSet ProductSet1 { get; set; }
    }
}
