//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int rec_id { get; set; }
        public Nullable<double> rec_sum { get; set; }
        public int rec_number { get; set; }
        public Nullable<System.DateTime> rec_date { get; set; }
        public Nullable<int> rec_amount { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> set_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        public virtual ProductNew ProductNew { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
